// =============================================================
// Tanipedia — 谷澤語録データ
// 全語録を一元管理。新語追加はここに書くだけでOK。
// =============================================================

const TANIPEDIA_DATA = {
  meta: {
    title: "📚 Tanipedia — 谷澤語録 非公式百科",
    established: "2026/2/18",
    totalWords: 51,
    operator: "CHIKUWA・EXPRESS",
    researchers: ["sasakurers", "Kitung", "Gobo★", "くまもん"],
    origin: "匿名T",
    pageOperator: "カイロス",
  },

  // 品詞マスタ（説明・バッジ色）
  partOfSpeech: {
    谷澤詞:     { desc: "廃止。谷澤語最初の品詞。原点にして頂点。", color: "#6b7280" },
    谷澤名詞:   { desc: "谷澤が発言した言葉", color: "#3b82f6" },
    谷澤他詞:   { desc: "谷澤以外の人物から谷澤への言葉", color: "#8b5cf6" },
    谷澤動詞:   { desc: "谷澤に関連する動詞", color: "#10b981" },
    谷澤英詞:   { desc: "英語由来の言葉（例：セタァップ、ナァディ）", color: "#f59e0b" },
    谷澤漢詞:   { desc: "特殊な読み方をする漢字（級位なし・意味なし）", color: "#ef4444" },
    谷澤接続助詞: { desc: "は・の・を・に など接続詞的役割", color: "#ec4899" },
    谷澤文詞:   { desc: "発言単体で文章が完結する語", color: "#0ea5e9" },
    谷澤単詞:   { desc: "発言単体で文章が完結しない語（単語含む）", color: "#64748b" },
    谷澤形容詞: { desc: "状態・容姿・関連状態を表す語（優先度高）", color: "#f97316" },
    谷澤疑問詞: { desc: "疑問形の発言（優先度高）", color: "#a855f7" },
    谷澤命令詞: { desc: "命令形の発言（優先度高）", color: "#dc2626" },
    なし:       { desc: "特殊項目（法則・概念）", color: "#9ca3af" },
  },

  // 級マスタ（表示名・バッジスタイル）
  levels: {
    "谷級": { label: "🏅 谷級", order: 0, class: "level-tani" },
    "1級":  { label: "🥇 1級", order: 1, class: "level-1" },
    "2級":  { label: "🥈 2級", order: 2, class: "level-2" },
    "3級":  { label: "🎖 3級", order: 3, class: "level-3" },
    "4級":  { label: "📘 4級", order: 4, class: "level-4" },
    "5級":  { label: "📗 5級", order: 5, class: "level-5" },
  },

  // 谷澤法則
  laws: [
    { name: "谷澤議論法則", content: "議論で不利になると必ず「話を変える」か「言い訳をして」有利な方向へ動かす" },
    { name: "谷澤追跡法則", content: "ちょっかいをかけると、または理不尽に、しつこく追いかけてくる" },
    { name: "谷澤ST法則",   content: "下校STで筆箱を無意識に回転させて遊ぶ。また「はい/みんな静かに」と発言する" },
    { name: "谷澤沈黙法則", content: "先生（草間/吉崎）に勝とうとするも必ず谷澤が論破される" },
    { name: "谷澤語源法則", content: "議論相手が言葉の語源を知らないと発言権なし、と主張する独裁的な考え方" },
  ],

  // 谷澤漢詞
  kanjiWords: [
    { kanji: "浅", reading: "アザ" },
    { kanji: "楽", reading: "リャク" },
  ],

  // 語録本体
  // id は URLスラッグとして使用（英数字・ハイフン推奨）
  words: [
    // ===== 谷級 =====
    {
      id: "omee-ga-ha",
      title: "オメェが〜 / オメェは〜",
      star: false,
      level: "谷級",
      pos: ["谷澤接続助詞"],
      body: "「が」「は」を入れることでオメェ（主語）とその後の文章をつなぐ重要な役割を果たす。",
      extra: "法則名：谷澤接続主格法",
    },
    {
      id: "omee-no",
      title: "オメェの〜",
      star: false,
      level: "谷級",
      pos: ["谷澤接続助詞"],
      body: "「の」を入れることでオメェ（主語）とその後の文章をつなぐ重要な役割を果たす。",
      extra: "法則名：谷澤接続所有格法",
    },
    {
      id: "omee-wo-ni",
      title: "オメェを〜 / オメェに〜",
      star: false,
      level: "谷級",
      pos: ["谷澤接続助詞"],
      body: "「を」「に」を入れることでオメェ（主語）とその後の文章をつなぐ重要な役割を果たす。",
      extra: "法則名：谷澤接続目的格法",
    },
    {
      id: "tani-the-hand",
      title: "谷 the ハンド",
      star: false,
      level: "谷級",
      pos: ["谷澤形容詞"],
      body: "谷澤が相手の腕を掴んでいる状態を表す。だが、大抵は同じような意味の「谷ギレ」が使用される。",
    },
    {
      id: "tanigire",
      title: "谷ギレ",
      star: false,
      level: "谷級",
      pos: ["谷澤形容詞"],
      body: "谷澤が怒っている状態のこと。",
    },

    // ===== 1級 =====
    {
      id: "tani-kahoutaisoku",
      title: "谷澤加法法則",
      star: true,
      level: "1級",
      pos: ["なし"],
      body: "tani＋5 ＝ ＋5tani（加法の場合は5taniの1番左に＋を付ける。）\nこれを、谷澤加法法則と言う。",
    },
    {
      id: "tani-jouhou-housoku",
      title: "谷澤乗法法則",
      star: true,
      level: "1級",
      pos: ["なし"],
      body: "tani×5 ＝ 5tani（乗法の場合は＋を付けず5taniのままにする。）\nこれを谷澤乗法法則と言う。",
      extra: "減法・除法は玄人向けのため記述なし。",
    },
    {
      id: "yatteii-koto",
      title: "やっていいこととやってよくない事があるんだよ。",
      star: true,
      level: "1級",
      pos: ["谷澤文詞"],
      body: "谷澤語の中では珍しく、至極真っ当な発言である。物事には善悪があるが、善は好まれ、悪は避けられる訳ではない。つまり、やってよくないが好まれる事がある。",
    },
    {
      id: "shi-iii-zuka-ni",
      title: "しイイイずかにイイイ",
      star: false,
      level: "1級",
      pos: ["谷澤単詞"],
      body: "静かにして欲しいという意図の発言。文字の表記から見て発言をした谷澤も声量が大きいということは間違いないだろう。",
    },
    {
      id: "sonotoki-ga-okita-toki",
      title: "その時が起きた時",
      star: false,
      level: "1級",
      pos: ["谷澤形容詞"],
      body: "その時の物事が起こる様子を表す。一見破綻しているような日本語だが、場面次第では正しくなる。",
    },
    {
      id: "sonotoki-boku-ga",
      title: "その時僕が初めて言った時",
      star: false,
      level: "1級",
      pos: ["谷澤形容詞"],
      body: "「僕が初めて言った時」のことを表す。こちらは日本語として破綻している。学力が非常に高い谷澤ですら日本語を間違えるのだから、日本語は難度が高いということが伺える。",
    },
    {
      id: "megane-kakete-ru",
      title: "メガネかけてるからって完全に見えるわけじゃないんだよ。",
      star: false,
      level: "1級",
      pos: ["谷澤文詞"],
      body: "メガネは視力が増長する道具だが、かけてさえいれば必ず裸眼視力の良い人と同等に見える訳ではないため、間違っていないかもしれない。",
    },
    {
      id: "naughty",
      title: "naughty（ナァディ）",
      star: false,
      level: "1級",
      pos: ["谷澤英詞"],
      body: "意味は「いたずら」。英語の naughty（いたずらな）から来ているが、naughty 自体は「いたずらな」という形容詞なので注意が必要。",
    },
    {
      id: "syoyuken-wa-boku",
      title: "所有権は僕が持ってるから僕のだ！",
      star: false,
      level: "1級",
      pos: ["谷澤文詞"],
      body: "その物事の所有権が谷澤にあるエビデンスが無いのに、所有権は自分にあると言い張る谷澤のセリフ。",
    },

    // ===== 2級 =====
    {
      id: "tani-infinity",
      title: "tani（タニ・インフィニティ・マセマーティクス）",
      star: true,
      level: "2級",
      pos: ["なし"],
      body: "正式名称：tani∞mathematics。理系教科での谷澤の表記。\n表記優先順位：1.2.3 ≧ tani ≧ a.b.c\n例式：tani×5² ＝ 25tani（5²を先に解く）",
    },
    {
      id: "tani-shiki-ra-gyou",
      title: "谷式ら行規則変化",
      star: true,
      level: "2級",
      pos: ["なし"],
      body: "ラ → リャ　/　ル → ドゥ　/　レ → リェ（谷式レ不規則変化あり）\nごくたまに「ル」「ラ」が通常の発言になる時がある（約2%）。",
    },
    {
      id: "tani-gui",
      title: "谷喰い",
      star: true,
      level: "2級",
      pos: ["谷澤動詞", "谷澤他詞"],
      body: "食品を口いっぱいに詰め込んでから半分だけ飲み込み、また口いっぱいに詰め込む……を繰り返す谷澤特有の伝統的な食事方法。\n研究員の観察の間、食事中に口が閉じた観察例なし。",
    },
    {
      id: "machigai-machigae",
      title: "間違いました間違えました",
      star: true,
      level: "2級",
      pos: ["谷澤文詞"],
      body: "以前までは「間違えたことに対して何かの拍子で二回言った」vs「『間違いた』と言い間違えたことに『間違えた』と言った」の二説があったが、最近後者で確定した。",
    },
    {
      id: "kujaku-ma-pyu",
      title: "クジャクマピュピャピュ",
      star: false,
      level: "2級",
      pos: ["谷澤名詞"],
      body: "「クジャクヤママユ」（蛾の一種）を指す。\n支離滅裂な文字列でもある程度意味が通じる日本語は、やっぱり簡単なのかもしれない。",
    },
    {
      id: "jibun-de-itteru",
      title: "自分で言っている意味がわかりません。",
      star: false,
      level: "2級",
      pos: ["谷澤文詞"],
      body: "自分（谷澤）の発言が後々わからなくなったり、矛盾してきたりしている状況だが、自分の発言の過ちは認めない言い回し。",
    },
    {
      id: "setaappu",
      title: "セタァップ",
      star: false,
      level: "2級",
      pos: ["谷澤英詞"],
      body: "意味は「建てる」。おそらく英語で「立てる・掲げる・据える」などを意味する「set up」が由来。",
    },
    {
      id: "daisan-sha",
      title: "第三者は黙っとけ",
      star: false,
      level: "2級",
      pos: ["谷澤命令詞"],
      body: "第三者に対して高圧的に黙らせる場合に使用される。第三者に論破されそうになった場合も都合よく使用される。",
    },
    {
      id: "tani-ne",
      title: "谷寝",
      star: false,
      level: "2級",
      pos: ["谷澤動詞"],
      body: "谷澤特有の寝方。具体的な寝方についての記述はない。",
    },
    {
      id: "tani-the-rush",
      title: "谷 the ラッシュ",
      star: false,
      level: "2級",
      pos: ["谷澤動詞"],
      body: "谷澤が無双（に準ずる行為）をしている時の様子を指す。普段舐められがちな谷澤だが、そのポテンシャルは測り知れない。",
    },
    {
      id: "chotto-naguru",
      title: "ちょっと殴るかな",
      star: false,
      level: "2級",
      pos: ["谷澤名詞"],
      body: "谷澤の名言の一つ。「手が出るぞ」という谷澤なりの威嚇のようだが、あまり痛くなさそうな気もする。",
    },
    {
      id: "nani-wo-iitai",
      title: "何を言いたいんだお前ら！",
      star: false,
      level: "2級",
      pos: ["谷澤疑問詞"],
      body: "相手（複数）の主張が理解できない、または筋が通らないと感じた時に、怒り・呆れの感情をこめて問いただす表現。",
    },
    {
      id: "purya-morye-ryu",
      title: "プリャモリェリュ",
      star: false,
      level: "2級",
      pos: ["谷澤名詞"],
      body: "日本語で言う「プラモデル」のこと。\n40%しか発音できていない。",
      extra: "「プラモデル」に対応する英語は存在しないため、谷澤英詞には当たらない。",
    },
    {
      id: "bukkowaredou",
      title: "ぶっ壊れドゥ / 落ちドゥ / 登ドゥ",
      star: false,
      level: "2級",
      pos: ["谷澤動詞"],
      body: "「る」→「ドゥ」と発音するという性質は同じため、まとめて記述。\n\nぶっ壊れドゥ → 壊れる\n落ちドゥ → 落ちる\n登ドゥ → 登る",
    },
    {
      id: "yoku-wakarimasen",
      title: "よく分かりませんでした。",
      star: false,
      level: "2級",
      pos: ["谷澤文詞"],
      body: "目上の相手の発言の意図が理解できない時に使用される。",
    },

    // ===== 3級 =====
    {
      id: "iya-chigaimasu",
      title: "いや、違います",
      star: false,
      level: "3級",
      pos: ["谷澤文詞"],
      body: "目上の相手の意見を否定する時に使用される。目上・目下で態度が変わるのは、人間として正しい行動だ。",
    },
    {
      id: "suware",
      title: "座れ！",
      star: false,
      level: "3級",
      pos: ["谷澤命令詞"],
      body: "相手に対して座るという動作を強制、または命令する際に使用される非常に高圧的な表現。",
    },
    {
      id: "soieba-shitteru",
      title: "そういえば知ってる",
      star: false,
      level: "3級",
      pos: ["谷澤文詞"],
      body: "谷澤がわからない問題で他の人間が回答した際などに、謎の見栄っ張りで知ってるアピールをする時に使用される。",
    },
    {
      id: "zakenна",
      title: "っざけんな",
      star: false,
      level: "3級",
      pos: ["谷澤命令詞"],
      body: "谷澤が理不尽にキレる時に谷澤本人が言う。ふざけているのはどっちだよ……",
    },
    {
      id: "dudududu",
      title: "ドゥドゥドゥー（以下略）",
      star: false,
      level: "3級",
      pos: ["谷澤名詞"],
      body: "音楽の授業で「君をのせて」テノールパートの「ルルルー（以下略）」の部分を「ドゥドゥドゥー（以下略）」と言ったことから誕生。\nやはり谷澤は「ル」が発音できない。",
    },
    {
      id: "nani-wo-shitai-ou",
      title: "何を死体王？",
      star: false,
      level: "3級",
      pos: ["谷澤疑問詞"],
      body: "相手の行動に対する目的・意図を尋ねる言葉。「何をしたいの？」の谷澤語版。",
    },
    {
      id: "nani-wo-shiteirunda",
      title: "何をしているんだ一体",
      star: false,
      level: "3級",
      pos: ["谷澤名詞"],
      body: "R7・1-5名言集に収録された谷澤の代表的名言。\n相手に対し、「何が目的でそんなことをしているのか」と問う際に使用される。",
    },
    {
      id: "minna-shizuka-ni",
      title: "みんな静かに！",
      star: false,
      level: "3級",
      pos: ["谷澤文詞"],
      body: "静かにすることを求める言葉。\n特定の人にしか言わないのにもかかわらず、「みんな」と言っている。連帯責任。",
    },

    // ===== 4級 =====
    {
      id: "ittai-nani-wo",
      title: "一体何をしているの？",
      star: false,
      level: "4級",
      pos: ["谷澤疑問詞"],
      body: "適当な時にとりあえず言っておけばいいと思っている。意味についての記述はない。",
    },
    {
      id: "otoshiana",
      title: "落とし穴があるんですよ",
      star: false,
      level: "4級",
      pos: ["谷澤文詞"],
      body: "物事の裏に隠された致命的な欠点・危険・策略を告げる時に使用される。だが、大抵は無い。",
    },
    {
      id: "omee-ga-tilde",
      title: "オメェ（お前）が〜",
      star: false,
      level: "4級",
      pos: ["谷澤詞"],
      body: "相手に自分の責任を押し付ける際に使用される。\n責任転嫁は人間としては間違っているかもしれないが、生物としては一番の正解である。",
    },
    {
      id: "dua",
      title: "ドゥアー",
      star: false,
      level: "4級",
      pos: ["谷澤英詞"],
      body: "日本語で言う「ルアー」のこと。",
    },
    {
      id: "duudu",
      title: "ドゥードゥ",
      star: false,
      level: "4級",
      pos: ["谷澤英詞"],
      body: "日本語で言う「ルール」のこと。",
    },

    // ===== 5級 =====
    {
      id: "hai",
      title: "はい",
      star: true,
      level: "5級",
      pos: ["谷澤単詞"],
      body: "質問への肯定。一見一般日本語と混同されがちだが、イントネーションが異なる。\n\n一般日本語：は→い→\n谷澤語：は→い↓ / は↓い↓",
    },
    {
      id: "aitsu",
      title: "アイツ（彼奴）",
      star: false,
      level: "5級",
      pos: ["谷澤名詞"],
      body: "第三者の名称。一般的な日本語。",
    },
    {
      id: "e",
      title: "え？",
      star: false,
      level: "5級",
      pos: ["谷澤疑問詞"],
      body: "相手（主に坂中海翔）へのツッコミに使用される。",
    },
    {
      id: "omee",
      title: "オメェ（お前）",
      star: false,
      level: "5級",
      pos: ["谷澤名詞"],
      body: "第二者（相手）を指す。一般的な日本語ではない。",
    },
    {
      id: "ita",
      title: "イタ",
      star: false,
      level: "5級",
      pos: ["谷澤単詞"],
      body: "谷澤が物が落ちた時に言う。何がイタなのだろうか。",
    },
  ],
};

// IDから語録を検索するユーティリティ
function getWordById(id) {
  return TANIPEDIA_DATA.words.find(w => w.id === id) || null;
}

// 級でフィルタ
function getWordsByLevel(level) {
  return TANIPEDIA_DATA.words.filter(w => w.level === level);
}
